spring:
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 123.60.110.230
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual #配置 Consumer 手动提交

